In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [9]:
train_df = pd.read_csv("../gait-data/train_set.csv")
labels = pd.read_csv("../gait-data/labels_train_set.csv")
merged_df = pd.merge(train_df, labels, on="ID")
merged_df.sample(10)

,ID,Subject,Session,Time:512Hz,FP1,FP2,F3,F4,FC1,FC2,...,Cz,CP2,CP1,P4,Pz,P3,O2,O1,time,angle
1347160,1347160,SCI2,12,229.621094,6298.584473,6214.648926,-9947.461914,-8864.649414,12396.143555,-10682.911133,...,4590.527832,7281.885254,1.657505e+04,-4334.180176,15960.108398,-4641.992676,-5094.873535,-5912.256348,229.621094,0.899931
225070,225070,SCI2,3,20.589844,-15185.645508,481.640656,-14076.221680,-1495.800903,-9828.663086,-16488.332031,...,-13277.930664,-10875.879883,-1.045195e+08,-23482.912109,-1539.355591,-14482.911133,-22178.908203,-20695.851562,20.589844,-5.011249
2268028,2268028,SCI3,4,104.839844,6216.357910,-13310.840820,-2549.560791,-10803.760742,-2625.000244,-7023.096191,...,-8258.057617,-5499.658691,-9.964796e+03,2999.414307,-1809.716919,10169.874023,6872.412598,8947.168945,104.839844,-101.765387
1235526,1235526,SCI2,12,11.585938,5398.584473,6454.639160,-10341.993164,-8888.672852,12725.928711,-10881.299805,...,5196.729004,6912.744629,1.681226e+04,-4318.555176,16451.076172,-4889.893066,-3568.017822,-6152.490723,11.585938,8.494190
976017,976017,SCI2,9,47.283203,7528.125488,16908.400391,10540.723633,6886.182129,-2667.968994,-12694.874023,...,5718.750488,6861.475098,1.254683e+04,9047.754883,166.992203,18127.394531,2396.679932,7076.318848,47.283203,-6.929474
2763774,2763774,SCI3,10,172.031250,-2597.851807,-4722.070801,-7121.777832,1934.912231,9579.346680,4435.840332,...,-11369.874023,-3122.802979,-7.116114e+03,14685.791992,-9075.928711,3960.742432,18124.025391,14811.866211,172.031250,-9.999655
2385399,2385399,SCI3,5,33.517578,6982.080566,-13737.696289,-947.851624,-10682.227539,-2133.984619,-6775.684082,...,-7952.441895,-4579.150879,-9.422022e+03,5067.187988,-768.798889,9949.170898,6944.824707,8831.446289,33.517578,54.819078
2250074,2250074,SCI3,4,69.773438,6272.021973,-13314.209961,-2361.426025,-10728.907227,-2567.138916,-6960.547363,...,-8256.885742,-5527.148926,-9.888575e+03,3108.349854,-1710.595825,10180.127930,6856.104004,8995.557617,69.773438,-62.528991
2249218,2249218,SCI3,4,68.101562,6299.365723,-13314.942383,-2341.064697,-10736.670898,-2577.929932,-6961.084473,...,-8281.836914,-5539.551270,-9.901319e+03,3126.172119,-1707.177856,10175.196289,6831.982910,8993.409180,68.101562,-58.571336
199375,199375,SCI2,2,270.404297,-15165.674805,792.529358,-13150.391602,-2187.256104,-10237.159180,-15550.245117,...,-13998.243164,-12223.145508,-1.045348e+08,-22760.744141,-1792.334106,-13201.368164,-20846.193359,-19574.806641,270.404297,-6.474106

              ID        time       angle
0              0    0.000000    1.057401
1              1    0.001953    1.075232
2              2    0.003906    1.089365
3              3    0.005859    1.099761
4              4    0.007812    1.106410
...          ...         ...         ...
3048425  3048425  127.990234  124.382060
3048426  3048426  127.992188  124.408879
3048427  3048427  127.994141  124.410576
3048428  3048428  127.996094  124.386556
3048429  3048429  127.998047  124.336493

[3048430 rows x 3 columns]

In [14]:
merged_df = merged_df.sort_values(by=["Subject", "Session", "Time:512Hz"])

In [28]:
subject1_session1 = merged_df[(merged_df['Subject'] == "SCI2") & (merged_df['Session'] == 1)]

In [29]:
subject1_session1

,ID,Subject,Session,Time:512Hz,FP1,FP2,F3,F4,FC1,FC2,...,Cz,CP2,CP1,P4,Pz,P3,O2,O1,time,angle
0,0,SCI2,1,0.000000,-15006.495117,760.498108,-14070.362305,-1148.193481,-9447.022461,-16526.857422,...,-12786.866211,-10324.366211,-104514664.0,-23172.169922,-1313.183716,-14525.928711,-22304.298828,-20537.404297,0.000000,1.057401
1,1,SCI2,1,0.001953,-15006.446289,750.927795,-14067.481445,-1145.996216,-9448.047852,-16520.363281,...,-12781.006836,-10316.358398,-104514664.0,-23159.816406,-1312.304810,-14525.098633,-22321.095703,-20543.654297,0.001953,1.075232
2,2,SCI2,1,0.003906,-15025.928711,746.826233,-14080.225586,-1126.318481,-9455.274414,-16515.675781,...,-12785.254883,-10325.147461,-104514680.0,-23177.687500,-1317.431763,-14528.809570,-22313.722656,-20539.796875,0.003906,1.089365
3,3,SCI2,1,0.005859,-15005.372070,768.261780,-14069.483398,-1135.888794,-9457.618164,-16527.052734,...,-12792.481445,-10331.153320,-104514656.0,-23187.550781,-1326.904419,-14546.680664,-22341.408203,-20583.449219,0.005859,1.099761
4,4,SCI2,1,0.007812,-15004.834961,764.160217,-14071.338867,-1146.728638,-9451.661133,-16524.074219,...,-12793.311523,-10327.881836,-104514648.0,-23174.171875,-1325.390747,-14547.071289,-22339.552734,-20578.468750,0.007812,1.106410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60923,60923,SCI2,1,118.990234,-15166.944336,379.834015,-14381.739258,-1288.134888,-9582.715820,-16685.841797,...,-12949.317383,-10454.151367,-104526664.0,-23459.621094,-1323.291138,-14719.922852,-22516.945312,-20733.009766,118.990234,2.112523
60924,60924,SCI2,1,118.992188,-15169.874023,383.251984,-14373.975586,-1281.347778,-9576.465820,-16681.789062,...,-12943.848633,-10451.563477,-104526664.0,-23467.775391,-1319.970825,-14711.866211,-22506.447266,-20713.576172,118.992188,2.145067
60925,60925,SCI2,1,118.994141,-15161.963867,384.570343,-14370.313477,-1299.023560,-9576.563477,-16691.750000,...,-12945.459961,-10454.346680,-104526648.0,-23467.873047,-1320.410278,-14714.405273,-22514.113281,-20729.933594,118.994141,2.176758
60926,60926,SCI2,1,118.996094,-15163.477539,372.705109,-14372.706055,-1283.300903,-9573.633789,-16678.908203,...,-12942.041992,-10446.973633,-104526656.0,-23461.623047,-1321.289185,-14712.354492,-22515.089844,-20729.933594,118.996094,2.207950
60927,60927,SCI2,1,118.998047,-15163.477539,372.705109,-14372.706055,-1283.300903,-9573.633789,-16678.908203,...,-12942.041992,-10446.973633,-104526656.0,-23461.623047,-1321.289185,-14712.354492,-22515.089844,-20729.933594,118.998047,2.239003

In [32]:
fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x=subject1_session1['time'].head(5000),
        y=subject1_session1['angle'].head(5000),
        mode='lines',
        name='Angle',
    )
)
fig.update_layout(
    title='Foot Angle Over Time (from first 100 rows of labels_df)',
    xaxis_title='Time (s)',
    yaxis_title='Angle (radians)',
    width=1200,
    height=600,
)
fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)
fig.show()

In [ ]:
from train import build_windows_over_subject_session 

X_all, y_all, meta = build_windows_over_subject_session(
    merged_df,
    # feature_cols=eeg_cols,
    target_col="angle", 
    fs=512,
    window_s=1.0,
    stride_s=0.1,
    lag_s=0.1,
    return_meta=True
)

print(X_all.shape)  # (total_windows, T, num_channels)
print(y_all.shape)  # (total_windows,)
print(meta.head())

(59516, 512, 17)
(59516,)
   start_idx  end_idx_exclusive  y_idx  start_time  end_time    y_time  \
0          0                512    562    0.000000  0.998047  1.097656
1         51                563    613    0.099609  1.097656  1.197266
2        102                614    664    0.199219  1.197266  1.296875
3        153                665    715    0.298828  1.296875  1.396484
4        204                716    766    0.398438  1.396484  1.496094

  Subject  Session
0    SCI2        1
1    SCI2        1
2    SCI2        1
3    SCI2        1
4    SCI2        1

In [38]:
X_all.shape

(59516, 512, 17)